placeholder initial commit
github-insights/github-metrics pull request #1
Opened 2024-04-16 08:58 UTC by tomellm

#2 #4 Since there were some problems with permissions and the initial commit this is the placeholder pull request for the first initial commit.

Spring app with 4 modules created: 
- app
- domain
- webApi
- githubAdapter

Minimum dependencies added to each and a simple test to check that everything interacts correctly.

2024-04-16 12:09 UTC, bavodaniels requested changes

2024-04-16 12:09 UTC, bavodaniels commented on .idea/.gitignore
please add in the gitignore to ignore the .idea folder

2024-04-16 12:51 UTC, tomellm commented on .idea/.gitignore
should be resolved

2024-04-17 07:16 UTC, bavodaniels approved these changes

2024-04-17 07:18 UTC, merged